// app/layout.js
import { Inter } from 'next/font/google'; // Предполагаем, что Inter используется
import './globals.css';
import ClientLayoutWrapper from './ClientLayoutWrapper'; // Импорт обертки

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'PokerNext',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Обертка для клиентских скриптов */}
        <ClientLayoutWrapper>
          {children}
        </ClientLayoutWrapper>
      </body>
    </html>
  );
}
